image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache: &cargo_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/bin
    - .cargo/registry/index
    - .cargo/registry/cache
    - HandRanks.dat
  policy: pull

stages:
  - prepare
  - verify

prepare:
  stage: prepare
  cache:
    <<: *cargo_cache
    policy: pull-push
  script:
    - |
      if [ -e HandRanks.dat ]; then
        echo "HandRanks.dat already exists"
      else
        curl -o HandRanks.dat https://raw.githubusercontent.com/tommy-a/zetebot/master/src/data/HandRanks.dat
      fi
    - cargo fetch

lint:
  stage: verify
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -- -D warnings

format:
  stage: verify
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

test:
  stage: verify
  script:
    - cargo test --verbose

