image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

stages:
  - test

test:cargo:
  stage: test
  before_script:
    - |
      if [ -e HandRanks.dat ]; then
        echo "HandRanks.dat already exists"
      else
        curl -o HandRanks.dat https://raw.githubusercontent.com/tommy-a/zetebot/master/src/data/HandRanks.dat
      fi
  cache:
    key: testcache
    paths:
      - HandRanks.dat
      - .cargo
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose

